LICENCE_PLATE_DROPDOWN = 'licence-plate-dropdown-event-trail'
DATE_PICKER = 'date-picker-event-trail'
MAP_GROUP_LAYER = 'map-group-layer-event-trail'
SLIDER = 'slider-event-trail'
CIRCLE_MARKER = 'circle-marker-event-trail'
